# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Error(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: str=None, message: str=None, more_info: List[str]=None):  # noqa: E501
        """Error - a model defined in Swagger

        :param code: The code of this Error.  # noqa: E501
        :type code: str
        :param message: The message of this Error.  # noqa: E501
        :type message: str
        :param more_info: The more_info of this Error.  # noqa: E501
        :type more_info: List[str]
        """
        self.swagger_types = {
            'code': str,
            'message': str,
            'more_info': List[str]
        }

        self.attribute_map = {
            'code': 'Code',
            'message': 'Message',
            'more_info': 'MoreInfo'
        }

        self._code = code
        self._message = message
        self._more_info = more_info

    @classmethod
    def from_dict(cls, dikt) -> 'Error':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Error of this Error.  # noqa: E501
        :rtype: Error
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this Error.

          # noqa: E501

        :return: The code of this Error.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this Error.

          # noqa: E501

        :param code: The code of this Error.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this Error.

          # noqa: E501

        :return: The message of this Error.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this Error.

          # noqa: E501

        :param message: The message of this Error.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def more_info(self) -> List[str]:
        """Gets the more_info of this Error.

          # noqa: E501

        :return: The more_info of this Error.
        :rtype: List[str]
        """
        return self._more_info

    @more_info.setter
    def more_info(self, more_info: List[str]):
        """Sets the more_info of this Error.

          # noqa: E501

        :param more_info: The more_info of this Error.
        :type more_info: List[str]
        """
        if more_info is None:
            raise ValueError("Invalid value for `more_info`, must not be `None`")  # noqa: E501

        self._more_info = more_info
