# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.error import Error  # noqa: F401,E501
from swagger_server import util


class Errors(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, error: List[Error]=None):  # noqa: E501
        """Errors - a model defined in Swagger

        :param error: The error of this Errors.  # noqa: E501
        :type error: List[Error]
        """
        self.swagger_types = {
            'error': List[Error]
        }

        self.attribute_map = {
            'error': 'Error'
        }

        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'Errors':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Errors of this Errors.  # noqa: E501
        :rtype: Errors
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> List[Error]:
        """Gets the error of this Errors.

          # noqa: E501

        :return: The error of this Errors.
        :rtype: List[Error]
        """
        return self._error

    @error.setter
    def error(self, error: List[Error]):
        """Sets the error of this Errors.

          # noqa: E501

        :param error: The error of this Errors.
        :type error: List[Error]
        """
        if error is None:
            raise ValueError("Invalid value for `error`, must not be `None`")  # noqa: E501

        self._error = error
