=begin
Ytel API V3

Ytel API version 3

OpenAPI spec version: 3.12

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class AreaMailController < ApplicationController

  def areamail_create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def areamail_delete
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def areamail_lists
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def areamail_view
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
