=begin
Ytel API V3

Ytel API version 3

OpenAPI spec version: 3.12

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class CallController < ApplicationController

  def calls_groupcall
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def calls_interruptcalls
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def calls_listcalls
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def calls_makecall
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def calls_makervm
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def calls_playaudios
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def calls_recordcalls
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def calls_senddigits
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def calls_viewcalldetail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def calls_viewcalls
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def calls_voiceeffect
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
