=begin
Ytel API V3

Ytel API version 3

OpenAPI spec version: 3.12

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class CarrierController < ApplicationController

  def carrier_lookup
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def carrier_lookuplist
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
