=begin
Ytel API V3

Ytel API version 3

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end
class ConferenceController < ApplicationController

  def conferences_add_participant
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def conferences_create_conference
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def conferences_deaf_mute_participant
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def conferences_hangup_participant
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def conferences_list_participant
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def conferences_listconference
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def conferences_play_audio
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def conferences_view_participant
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def conferences_viewconference
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
