=begin
Ytel API V3

Ytel API version 3

OpenAPI spec version: 3.12

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class ConferenceController < ApplicationController

  def conferences_add_participant
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def conferences_create_conference
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def conferences_deaf_mute_participant
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def conferences_hangup_participant
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def conferences_list_participant
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def conferences_listconference
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def conferences_play_audio
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def conferences_view_participant
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def conferences_viewconference
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
