=begin
Ytel API V3

Ytel API version 3

OpenAPI spec version: 3.12

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class EmailController < ApplicationController

  def email_addunsubscribesemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_deleteblocksemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_deletebouncesemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_deleteinvalidemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_deletespamemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_deleteunsubscribedemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_listblockemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_listbounceemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_listinvalidemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_listspamemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_listunsubscribedemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_sendemails
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
