=begin
Ytel API V3

Ytel API version 3

OpenAPI spec version: 3.11

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end
class EmailController < ApplicationController

  def email_addunsubscribesemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_deleteblocksemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_deletebouncesemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_deleteinvalidemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_deletespamemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_deleteunsubscribedemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_listblockemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_listbounceemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_listinvalidemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_listspamemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_listunsubscribedemail
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def email_sendemails
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
