=begin
Ytel API V3

Ytel API version 3

OpenAPI spec version: 3.12

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class PostCardController < ApplicationController

  def postcard_createpostcard
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def postcard_deletepostcard
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def postcard_listpostcard
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def postcard_viewpostcard
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
