=begin
Ytel API V3

Ytel API version 3

OpenAPI spec version: 3.12

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class ShortCodeController < ApplicationController

  def dedicatedshortcode_getinboundsms
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def dedicatedshortcode_listshortcode
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def dedicatedshortcode_sendsms
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def dedicatedshortcode_updateshortcode
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def dedicatedshortcode_viewshortcode
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shortcode_listsms
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def shortcode_viewsms
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
