=begin
Ytel API V3

Ytel API version 3

OpenAPI spec version: 3.12

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class SMSController < ApplicationController

  def sms_getinboundsms
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sms_listsms
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sms_sendsms
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sms_viewdetailsms
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def sms_viewsms
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
