=begin
Ytel API V3

Ytel API version 3

OpenAPI spec version: 3.12

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class SubAccountController < ApplicationController

  def user_createsubaccount
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_deletesubaccount
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def user_subaccountactivation
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
