=begin
Ytel API V3

Ytel API version 3

OpenAPI spec version: 3.12

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class TranscriptionController < ApplicationController

  def transcriptions_audiourltranscription
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def transcriptions_listtranscription
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def transcriptions_recordingtranscription
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def transcriptions_viewtranscription
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
