/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-11-21T17:51:00.851Z")

@Api(value = "usage", description = "the usage API")
public interface UsageApi {

    @ApiOperation(value = "List Usage", nickname = "usageListusage", notes = "Retrieve usage metrics regarding your Ytel account. The results includes inbound/outbound voice calls and inbound/outbound SMS messages as well as carrier lookup requests.", response = String.class, authorizations = {
        @Authorization(value = "auth")
    }, tags={ "Usage", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = String.class) })
    @RequestMapping(value = "/usage/listusage.json",
        produces = { "application/json" }, 
        consumes = { "application/x-www-form-urlencoded" },
        method = RequestMethod.POST)
    ResponseEntity<String> usageListusage(@ApiParam(value = "Filter usage results by product type.", allowableValues="0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13", defaultValue="0") @RequestParam(value="ProductCode", required=false)  String productCode,@ApiParam(value = "Filter usage objects by start date.", defaultValue="2016-09-06") @RequestParam(value="startDate", required=false)  String startDate,@ApiParam(value = "Filter usage objects by end date.", defaultValue="2016-09-06") @RequestParam(value="endDate", required=false)  String endDate,@ApiParam(value = "Will include all subaccount usage data") @RequestParam(value="IncludeSubAccounts", required=false)  String includeSubAccounts);

}
