/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger
// ActivateStatus : Choose account status either 0 or 1
type ActivateStatus int32

// List of ActivateStatus
const (
	1_ ActivateStatus = "1"
	0_ ActivateStatus = "0"
)
