/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Activate int32

// List of Activate
const (
	1_ Activate = "1"
	0_ Activate = "0"
)
