/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger
// AudioDirection : Audio Direction
type AudioDirection string

// List of AudioDirection
const (
	IN AudioDirection = "in"
	OUT AudioDirection = "out"
)
