/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AudioUrl string

// List of AudioUrl
const (
	MP3 AudioUrl = "mp3"
	WAV AudioUrl = "wav"
)
