/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger
// AudioFormat : Audio Format file type mp3 or wav
type AudioFormat string

// List of AudioFormat
const (
	MP3 AudioFormat = "mp3"
	WAV AudioFormat = "wav"
)
