/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger
// Direction : Play DTMF Direction & in play audio & sendDigit
type Direction string

// List of Direction
const (
	IN Direction = "in"
	OUT Direction = "out"
	BOTH Direction = "both"
)
