/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GroupConfirmFile string

// List of GroupConfirmFile
const (
	MP3 GroupConfirmFile = "mp3"
	WAV GroupConfirmFile = "wav"
)
