/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger
// HttpAction : Types Of Method
type HttpAction string

// List of HttpAction
const (
	GET HttpAction = "GET"
	POST HttpAction = "POST"
)
