/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger
// IfMachine : How Message360 should handle the receiving numbers voicemail machine
type IfMachine string

// List of IfMachine
const (
	CONTINUE_ IfMachine = "continue"
	HANGUP IfMachine = "hangup"
)
