/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger
// InterruptedCallStatus : Interrupted Call Status
type InterruptedCallStatus string

// List of InterruptedCallStatus
const (
	CANCELED InterruptedCallStatus = "canceled"
	COMPLETED InterruptedCallStatus = "completed"
)
