/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MergeNumber int32

// List of MergeNumber
const (
	0_ MergeNumber = "0"
	1_ MergeNumber = "1"
)
