/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger
// MergeNumberStatus : Choose sub account either merge or delete
type MergeNumberStatus int32

// List of MergeNumberStatus
const (
	0_ MergeNumberStatus = "0"
	1_ MergeNumberStatus = "1"
)
