/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Message struct {

	// 
	ApiVersion string `json:"ApiVersion"`

	// 
	MessageSid string `json:"MessageSid"`

	// 
	From string `json:"From"`

	// 
	To string `json:"To"`

	// 
	MessagePrice string `json:"MessagePrice"`

	// 
	Body string `json:"Body"`

	// 
	DateSent string `json:"DateSent"`

	// 
	Status string `json:"Status"`

	// 
	TemplateId string `json:"TemplateId"`

	TemplateData *TemplateData `json:"TemplateData"`
}
