/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger
// NumberType : Phone Number Type All,SMS or Voice
type NumberType string

// List of NumberType
const (
	ALL NumberType = "all"
	VOICE NumberType = "voice"
	SMS NumberType = "sms"
)
