/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Numbertype16 string

// List of Numbertype16
const (
	ALL Numbertype16 = "all"
	VOICE Numbertype16 = "voice"
	SMS Numbertype16 = "sms"
)
