/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PlayDtmfDirection string

// List of PlayDtmfDirection
const (
	IN PlayDtmfDirection = "in"
	OUT PlayDtmfDirection = "out"
	BOTH PlayDtmfDirection = "both"
)
