/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ProductCode27 int32

// List of ProductCode27
const (
	0_ ProductCode27 = "0"
	1_ ProductCode27 = "1"
	2_ ProductCode27 = "2"
	3_ ProductCode27 = "3"
	4_ ProductCode27 = "4"
	5_ ProductCode27 = "5"
	6_ ProductCode27 = "6"
	7_ ProductCode27 = "7"
	8_ ProductCode27 = "8"
	9_ ProductCode27 = "9"
	10_ ProductCode27 = "10"
	11_ ProductCode27 = "11"
	12_ ProductCode27 = "12"
	13_ ProductCode27 = "13"
)
