/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger
// ProductCode : Returns a list of all usage for a specific \"product\" or feature of Message360.
type ProductCode int32

// List of ProductCode
const (
	0_ ProductCode = "0"
	1_ ProductCode = "1"
	2_ ProductCode = "2"
	3_ ProductCode = "3"
	4_ ProductCode = "4"
	5_ ProductCode = "5"
	6_ ProductCode = "6"
	7_ ProductCode = "7"
	8_ ProductCode = "8"
	9_ ProductCode = "9"
	10_ ProductCode = "10"
	11_ ProductCode = "11"
	12_ ProductCode = "12"
	13_ ProductCode = "13"
)
