/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/api/v3/",
		Index,
	},

	Route{
		"AccountsViewaccount",
		strings.ToUpper("Post"),
		"/api/v3/accounts/viewaccount.json",
		AccountsViewaccount,
	},

	Route{
		"AddressCreateaddress",
		strings.ToUpper("Post"),
		"/api/v3/address/createaddress.json",
		AddressCreateaddress,
	},

	Route{
		"AddressDeleteaddress",
		strings.ToUpper("Post"),
		"/api/v3/address/deleteaddress.json",
		AddressDeleteaddress,
	},

	Route{
		"AddressListaddress",
		strings.ToUpper("Post"),
		"/api/v3/address/listaddress.json",
		AddressListaddress,
	},

	Route{
		"AddressVerifyaddress",
		strings.ToUpper("Post"),
		"/api/v3/address/verifyaddress.json",
		AddressVerifyaddress,
	},

	Route{
		"AddressViewaddress",
		strings.ToUpper("Post"),
		"/api/v3/address/viewaddress.json",
		AddressViewaddress,
	},

	Route{
		"AreamailCreate",
		strings.ToUpper("Post"),
		"/api/v3/areamail/create.json",
		AreamailCreate,
	},

	Route{
		"AreamailDelete",
		strings.ToUpper("Post"),
		"/api/v3/areamail/delete.json",
		AreamailDelete,
	},

	Route{
		"AreamailLists",
		strings.ToUpper("Post"),
		"/api/v3/areamail/lists.json",
		AreamailLists,
	},

	Route{
		"AreamailView",
		strings.ToUpper("Post"),
		"/api/v3/areamail/view.json",
		AreamailView,
	},

	Route{
		"CallsGroupcall",
		strings.ToUpper("Post"),
		"/api/v3/calls/groupcall.json",
		CallsGroupcall,
	},

	Route{
		"CallsInterruptcalls",
		strings.ToUpper("Post"),
		"/api/v3/calls/interruptcalls.json",
		CallsInterruptcalls,
	},

	Route{
		"CallsListcalls",
		strings.ToUpper("Post"),
		"/api/v3/calls/listcalls.json",
		CallsListcalls,
	},

	Route{
		"CallsMakecall",
		strings.ToUpper("Post"),
		"/api/v3/calls/makecall.json",
		CallsMakecall,
	},

	Route{
		"CallsMakervm",
		strings.ToUpper("Post"),
		"/api/v3/calls/makervm.json",
		CallsMakervm,
	},

	Route{
		"CallsPlayaudios",
		strings.ToUpper("Post"),
		"/api/v3/calls/playaudios.json",
		CallsPlayaudios,
	},

	Route{
		"CallsRecordcalls",
		strings.ToUpper("Post"),
		"/api/v3/calls/recordcalls.json",
		CallsRecordcalls,
	},

	Route{
		"CallsSenddigits",
		strings.ToUpper("Post"),
		"/api/v3/calls/senddigits.json",
		CallsSenddigits,
	},

	Route{
		"CallsViewcalldetail",
		strings.ToUpper("Post"),
		"/api/v3/calls/viewcalldetail.json",
		CallsViewcalldetail,
	},

	Route{
		"CallsViewcalls",
		strings.ToUpper("Post"),
		"/api/v3/calls/viewcalls.json",
		CallsViewcalls,
	},

	Route{
		"CallsVoiceeffect",
		strings.ToUpper("Post"),
		"/api/v3/calls/voiceeffect.json",
		CallsVoiceeffect,
	},

	Route{
		"CarrierLookup",
		strings.ToUpper("Post"),
		"/api/v3/carrier/lookup.json",
		CarrierLookup,
	},

	Route{
		"CarrierLookuplist",
		strings.ToUpper("Post"),
		"/api/v3/carrier/lookuplist.json",
		CarrierLookuplist,
	},

	Route{
		"ConferencesAddParticipant",
		strings.ToUpper("Post"),
		"/api/v3/conferences/addParticipant.json",
		ConferencesAddParticipant,
	},

	Route{
		"ConferencesCreateConference",
		strings.ToUpper("Post"),
		"/api/v3/conferences/createConference.json",
		ConferencesCreateConference,
	},

	Route{
		"ConferencesDeafMuteParticipant",
		strings.ToUpper("Post"),
		"/api/v3/conferences/deafMuteParticipant.json",
		ConferencesDeafMuteParticipant,
	},

	Route{
		"ConferencesHangupParticipant",
		strings.ToUpper("Post"),
		"/api/v3/conferences/hangupParticipant.json",
		ConferencesHangupParticipant,
	},

	Route{
		"ConferencesListParticipant",
		strings.ToUpper("Post"),
		"/api/v3/conferences/listParticipant.json",
		ConferencesListParticipant,
	},

	Route{
		"ConferencesListconference",
		strings.ToUpper("Post"),
		"/api/v3/conferences/listconference.json",
		ConferencesListconference,
	},

	Route{
		"ConferencesPlayAudio",
		strings.ToUpper("Post"),
		"/api/v3/conferences/playAudio.json",
		ConferencesPlayAudio,
	},

	Route{
		"ConferencesViewParticipant",
		strings.ToUpper("Post"),
		"/api/v3/conferences/viewParticipant.json",
		ConferencesViewParticipant,
	},

	Route{
		"ConferencesViewconference",
		strings.ToUpper("Post"),
		"/api/v3/conferences/viewconference.json",
		ConferencesViewconference,
	},

	Route{
		"EmailAddunsubscribesemail",
		strings.ToUpper("Post"),
		"/api/v3/email/addunsubscribesemail.json",
		EmailAddunsubscribesemail,
	},

	Route{
		"EmailDeleteblocksemail",
		strings.ToUpper("Post"),
		"/api/v3/email/deleteblocksemail.json",
		EmailDeleteblocksemail,
	},

	Route{
		"EmailDeletebouncesemail",
		strings.ToUpper("Post"),
		"/api/v3/email/deletebouncesemail.json",
		EmailDeletebouncesemail,
	},

	Route{
		"EmailDeleteinvalidemail",
		strings.ToUpper("Post"),
		"/api/v3/email/deleteinvalidemail.json",
		EmailDeleteinvalidemail,
	},

	Route{
		"EmailDeletespamemail",
		strings.ToUpper("Post"),
		"/api/v3/email/deletespamemail.json",
		EmailDeletespamemail,
	},

	Route{
		"EmailDeleteunsubscribedemail",
		strings.ToUpper("Post"),
		"/api/v3/email/deleteunsubscribedemail.json",
		EmailDeleteunsubscribedemail,
	},

	Route{
		"EmailListblockemail",
		strings.ToUpper("Post"),
		"/api/v3/email/listblockemail.json",
		EmailListblockemail,
	},

	Route{
		"EmailListbounceemail",
		strings.ToUpper("Post"),
		"/api/v3/email/listbounceemail.json",
		EmailListbounceemail,
	},

	Route{
		"EmailListinvalidemail",
		strings.ToUpper("Post"),
		"/api/v3/email/listinvalidemail.json",
		EmailListinvalidemail,
	},

	Route{
		"EmailListspamemail",
		strings.ToUpper("Post"),
		"/api/v3/email/listspamemail.json",
		EmailListspamemail,
	},

	Route{
		"EmailListunsubscribedemail",
		strings.ToUpper("Post"),
		"/api/v3/email/listunsubscribedemail.json",
		EmailListunsubscribedemail,
	},

	Route{
		"EmailSendemails",
		strings.ToUpper("Post"),
		"/api/v3/email/sendemails.json",
		EmailSendemails,
	},

	Route{
		"LetterCreate",
		strings.ToUpper("Post"),
		"/api/v3/letter/create.json",
		LetterCreate,
	},

	Route{
		"LetterDelete",
		strings.ToUpper("Post"),
		"/api/v3/letter/delete.json",
		LetterDelete,
	},

	Route{
		"LetterListsletter",
		strings.ToUpper("Post"),
		"/api/v3/letter/listsletter.json",
		LetterListsletter,
	},

	Route{
		"LetterViewletter",
		strings.ToUpper("Post"),
		"/api/v3/letter/viewletter.json",
		LetterViewletter,
	},

	Route{
		"IncomingphoneAvailablenumber",
		strings.ToUpper("Post"),
		"/api/v3/incomingphone/availablenumber.json",
		IncomingphoneAvailablenumber,
	},

	Route{
		"IncomingphoneBulkbuy",
		strings.ToUpper("Post"),
		"/api/v3/incomingphone/bulkbuy.json",
		IncomingphoneBulkbuy,
	},

	Route{
		"IncomingphoneBuynumber",
		strings.ToUpper("Post"),
		"/api/v3/incomingphone/buynumber.json",
		IncomingphoneBuynumber,
	},

	Route{
		"IncomingphoneGetdidscore",
		strings.ToUpper("Post"),
		"/api/v3/incomingphone/getdidscore.json",
		IncomingphoneGetdidscore,
	},

	Route{
		"IncomingphoneListnumber",
		strings.ToUpper("Post"),
		"/api/v3/incomingphone/listnumber.json",
		IncomingphoneListnumber,
	},

	Route{
		"IncomingphoneMassreleasenumber",
		strings.ToUpper("Post"),
		"/api/v3/incomingphone/massreleasenumber.json",
		IncomingphoneMassreleasenumber,
	},

	Route{
		"IncomingphoneMassupdatenumber",
		strings.ToUpper("Post"),
		"/api/v3/incomingphone/massupdatenumber.json",
		IncomingphoneMassupdatenumber,
	},

	Route{
		"IncomingphoneReleasenumberByResponseTypePost",
		strings.ToUpper("Post"),
		"/api/v3/incomingphone/releasenumber.{ResponseType}",
		IncomingphoneReleasenumberByResponseTypePost,
	},

	Route{
		"IncomingphoneTransferphonenumbers",
		strings.ToUpper("Post"),
		"/api/v3/incomingphone/transferphonenumbers.json",
		IncomingphoneTransferphonenumbers,
	},

	Route{
		"IncomingphoneUpdatenumber",
		strings.ToUpper("Post"),
		"/api/v3/incomingphone/updatenumber.json",
		IncomingphoneUpdatenumber,
	},

	Route{
		"IncomingphoneViewnumber",
		strings.ToUpper("Post"),
		"/api/v3/incomingphone/viewnumber.json",
		IncomingphoneViewnumber,
	},

	Route{
		"PostcardCreatepostcard",
		strings.ToUpper("Post"),
		"/api/v3/Postcard/createpostcard.json",
		PostcardCreatepostcard,
	},

	Route{
		"PostcardDeletepostcard",
		strings.ToUpper("Post"),
		"/api/v3/Postcard/deletepostcard.json",
		PostcardDeletepostcard,
	},

	Route{
		"PostcardListpostcard",
		strings.ToUpper("Post"),
		"/api/v3/Postcard/listpostcard.json",
		PostcardListpostcard,
	},

	Route{
		"PostcardViewpostcard",
		strings.ToUpper("Post"),
		"/api/v3/Postcard/viewpostcard.json",
		PostcardViewpostcard,
	},

	Route{
		"RecordingDeleterecording",
		strings.ToUpper("Post"),
		"/api/v3/recording/deleterecording.json",
		RecordingDeleterecording,
	},

	Route{
		"RecordingListrecording",
		strings.ToUpper("Post"),
		"/api/v3/recording/listrecording.json",
		RecordingListrecording,
	},

	Route{
		"RecordingViewrecording",
		strings.ToUpper("Post"),
		"/api/v3/recording/viewrecording.json",
		RecordingViewrecording,
	},

	Route{
		"SmsGetinboundsms",
		strings.ToUpper("Post"),
		"/api/v3/sms/getinboundsms.json",
		SmsGetinboundsms,
	},

	Route{
		"SmsListsms",
		strings.ToUpper("Post"),
		"/api/v3/sms/listsms.json",
		SmsListsms,
	},

	Route{
		"SmsSendsms",
		strings.ToUpper("Post"),
		"/api/v3/sms/sendsms.json",
		SmsSendsms,
	},

	Route{
		"SmsViewdetailsms",
		strings.ToUpper("Post"),
		"/api/v3/sms/viewdetailsms.json",
		SmsViewdetailsms,
	},

	Route{
		"SmsViewsms",
		strings.ToUpper("Post"),
		"/api/v3/sms/viewsms.json",
		SmsViewsms,
	},

	Route{
		"KeywordLists",
		strings.ToUpper("Post"),
		"/api/v3/keyword/lists.json",
		KeywordLists,
	},

	Route{
		"KeywordView",
		strings.ToUpper("Post"),
		"/api/v3/keyword/view.json",
		KeywordView,
	},

	Route{
		"ShortcodeGetinboundsms",
		strings.ToUpper("Post"),
		"/api/v3/shortcode/getinboundsms.json",
		ShortcodeGetinboundsms,
	},

	Route{
		"ShortcodeListshortcode",
		strings.ToUpper("Post"),
		"/api/v3/shortcode/listshortcode.json",
		ShortcodeListshortcode,
	},

	Route{
		"ShortcodeSendsms",
		strings.ToUpper("Post"),
		"/api/v3/shortcode/sendsms.json",
		ShortcodeSendsms,
	},

	Route{
		"ShortcodeUpdateshortcode",
		strings.ToUpper("Post"),
		"/api/v3/shortcode/updateshortcode.json",
		ShortcodeUpdateshortcode,
	},

	Route{
		"ShortcodeViewshortcode",
		strings.ToUpper("Post"),
		"/api/v3/shortcode/viewshortcode.json",
		ShortcodeViewshortcode,
	},

	Route{
		"TemplateLists",
		strings.ToUpper("Post"),
		"/api/v3/template/lists.json",
		TemplateLists,
	},

	Route{
		"TemplateView",
		strings.ToUpper("Post"),
		"/api/v3/template/view.json",
		TemplateView,
	},

	Route{
		"DedicatedshortcodeGetinboundsms",
		strings.ToUpper("Post"),
		"/api/v3/dedicatedshortcode/getinboundsms.json",
		DedicatedshortcodeGetinboundsms,
	},

	Route{
		"DedicatedshortcodeListshortcode",
		strings.ToUpper("Post"),
		"/api/v3/dedicatedshortcode/listshortcode.json",
		DedicatedshortcodeListshortcode,
	},

	Route{
		"DedicatedshortcodeSendsms",
		strings.ToUpper("Post"),
		"/api/v3/dedicatedshortcode/sendsms.json",
		DedicatedshortcodeSendsms,
	},

	Route{
		"DedicatedshortcodeUpdateshortcode",
		strings.ToUpper("Post"),
		"/api/v3/dedicatedshortcode/updateshortcode.json",
		DedicatedshortcodeUpdateshortcode,
	},

	Route{
		"DedicatedshortcodeViewshortcode",
		strings.ToUpper("Post"),
		"/api/v3/dedicatedshortcode/viewshortcode.json",
		DedicatedshortcodeViewshortcode,
	},

	Route{
		"ShortcodeListsms",
		strings.ToUpper("Post"),
		"/api/v3/shortcode/listsms.json",
		ShortcodeListsms,
	},

	Route{
		"ShortcodeViewsms",
		strings.ToUpper("Post"),
		"/api/v3/shortcode/viewsms.json",
		ShortcodeViewsms,
	},

	Route{
		"UserCreatesubaccount",
		strings.ToUpper("Post"),
		"/api/v3/user/createsubaccount.json",
		UserCreatesubaccount,
	},

	Route{
		"UserDeletesubaccount",
		strings.ToUpper("Post"),
		"/api/v3/user/deletesubaccount.json",
		UserDeletesubaccount,
	},

	Route{
		"UserSubaccountactivation",
		strings.ToUpper("Post"),
		"/api/v3/user/subaccountactivation.json",
		UserSubaccountactivation,
	},

	Route{
		"TranscriptionsAudiourltranscription",
		strings.ToUpper("Post"),
		"/api/v3/transcriptions/audiourltranscription.json",
		TranscriptionsAudiourltranscription,
	},

	Route{
		"TranscriptionsListtranscription",
		strings.ToUpper("Post"),
		"/api/v3/transcriptions/listtranscription.json",
		TranscriptionsListtranscription,
	},

	Route{
		"TranscriptionsRecordingtranscription",
		strings.ToUpper("Post"),
		"/api/v3/transcriptions/recordingtranscription.json",
		TranscriptionsRecordingtranscription,
	},

	Route{
		"TranscriptionsViewtranscription",
		strings.ToUpper("Post"),
		"/api/v3/transcriptions/viewtranscription.json",
		TranscriptionsViewtranscription,
	},

	Route{
		"UsageListusage",
		strings.ToUpper("Post"),
		"/api/v3/usage/listusage.json",
		UsageListusage,
	},
}
