/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger
// SendEmailAs : send email TEXT or HTML format
type SendEmailAs string

// List of SendEmailAs
const (
	TEXT SendEmailAs = "text"
	HTML SendEmailAs = "html"
)
