/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger
// Status : Transcription Status
type Status string

// List of Status
const (
	INPROGRESS Status = "inprogress"
	SUCCESS Status = "success"
	FAILURE Status = "failure"
)
