/*
 * Ytel API V3
 *
 * Ytel API version 3
 *
 * API version: 3.12
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Status24 string

// List of Status24
const (
	CANCELED Status24 = "canceled"
	COMPLETED Status24 = "completed"
)
