=begin
Ytel API V3

Ytel API version 3

OpenAPI spec version: 3.12

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class Message < ApplicationRecord
  validates_presence_of :api_version
  validates_presence_of :message_sid
  validates_presence_of :from
  validates_presence_of :to
  validates_presence_of :message_price
  validates_presence_of :body
  validates_presence_of :date_sent
  validates_presence_of :status
  validates_presence_of :template_id
  validates_presence_of :template_data

end
