=begin
Ytel API V3

Ytel API version 3

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end


class Message < ApplicationRecord
  validates_presence_of :api_version
  validates_presence_of :message_sid
  validates_presence_of :from
  validates_presence_of :to
  validates_presence_of :message_price
  validates_presence_of :body
  validates_presence_of :date_sent
  validates_presence_of :status
  validates_presence_of :template_id
  validates_presence_of :template_data

end
