=begin
Ytel API V3

Ytel API version 3

OpenAPI spec version: 3.12

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "activate".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "activate_status".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "audio_direction".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "audio_format".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "audio_url".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "direction".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "error".pluralize.to_sym, id: false do |t|
      t.string :code
      t.string :message
      t.string :more_info

      t.timestamps
    end

    create_table "errors".pluralize.to_sym, id: false do |t|
      t.string :error

      t.timestamps
    end

    create_table "fileformat".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "group_confirm_file".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "http_action".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "if_machine".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "interrupted_call_status".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "merge_number".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "merge_number_status".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "message".pluralize.to_sym, id: false do |t|
      t.string :api_version
      t.string :message_sid
      t.string :from
      t.string :to
      t.string :message_price
      t.string :body
      t.string :date_sent
      t.string :status
      t.string :template_id
      t.string :template_data

      t.timestamps
    end

    create_table "number_type".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "numbertype16".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "play_dtmf_direction".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "product_code".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "product_code27".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "send_email_as".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "status".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "status24".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

    create_table "template_data".pluralize.to_sym, id: false do |t|
      t.string :companyname
      t.string :otpcode

      t.timestamps
    end

    create_table "type".pluralize.to_sym, id: false do |t|

      t.timestamps
    end

  end
end
